#!/bin/bash
pushd "$(dirname $0)" > /dev/null
SCRIPTDIR="$(pwd)"
popd > /dev/null
WDIR="${SCRIPTDIR}/dwb-build"
OUTDIR="${SCRIPTDIR}/dwb-out"
PATCHEDDIR="${SCRIPTDIR}/patched"
rm -rf $WDIR $OUTDIR
#prepare dwb-gtk3 package
TGZNAME="dwb-gtk3-git"
TARBALL="https://aur.archlinux.org/packages/dw/${TGZNAME}/${TGZNAME}.tar.gz"
mkdir -p $WDIR
cd $WDIR
wget $TARBALL
tar xzf ${TGZNAME}.tar.gz
cd ${TGZNAME}
makepkg --asroot
mkdir -p $OUTDIR
mv dwb-gtk3*.tar.xz "${OUTDIR}/${TGZNAME}.tar.xz"
cd $SCRIPTDIR
rm -rf $WDIR
repo-add "${OUTDIR}/dwb-repo.db.tar.gz" "${OUTDIR}/${TGZNAME}.tar.xz"
#add patched cairo-git package
cp "${PATCHEDDIR}/cairo/cairo-git.tar.xz" "${OUTDIR}/cairo-git.tar.xz"
repo-add "${OUTDIR}/dwb-repo.db.tar.gz" "${OUTDIR}/cairo-git.tar.xz"
PACMANCONF=${SCRIPTDIR}/pacman.conf
sed -i '$ d' $PACMANCONF
echo -n "Server = file://${SCRIPTDIR}/dwb-out">>$PACMANCONF
